project_id = "jsptozrmlibvxzfkvrec"

[functions.get-subscription-status]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhooks]
verify_jwt = false

[functions.check-rate-limit]
verify_jwt = false

[functions.verify-maintenance-password]
verify_jwt = false

[functions.sanitize-user-metadata]
verify_jwt = true
